### PR TITLE
Add support for dlv exec

### LINKED ISSUE #5: Add dlv exec support
Thanks for this! This looks great!

I need to execute `dlv` using `dlv exec` because I work at Google and we use [Bazel](http://bazel.build), not the normal Go structure.

Is it possible to do this with `vim-delve`?

### LINKED ISSUE #8: Implement optional parameters for `delve#runCommand`
Implement optional parameters for `delve#runCommand`

### PR DESCRIPTION
**Pull request by sebdah**
This makes it possible to debug pre-built binaries.

Closes #5
Closes #8

### CODE REVIEW

**Comment by cflewis** [comment]
Something doesn't work quite right *in my case*. If I run `:DlvExec path/to/my/bin` from an empty nvim buffer, it works as expected. If I run it from a buffer populated with a file, it outputs:
```

could not launch process: fork/exec path/to/my/bin: no such file or directory                              
[Process exited 1]
```

`DlvExec` is trying to go relative from the file I am at, whereas I would like to go from the current working directory. I can believe that going relative is totally the right thing to do for most cases, but it doesn't work for me. I had to do this instead:

```
:execute 'DlvExec ' . getcwd() . '/path/to/my/bin'
```

If this is what you want, adding this to my vimrc is no problem for me. I just wanted to make sure you were aware :)

**Comment by sebdah** [comment]
Thanks for the quick feedback. I'll look this through later!

**Comment by sebdah** [comment]
I've written a fix that assumes nothing from the buffer context. This should get you a more natural behavior.

**Comment by sebdah** [comment]
If you can have a look @cflewis please do, otherwise I think I'll merge this tomorrow sometime. Thanks again for the feedback.

**Comment by cflewis** [comment]
LGTM! Awesome!

**Pull request merged**
